#!/usr/bin/env node

var decrypt = require('./src/decrypt');
var args    = process.argv.slice(2);
var key     = args[0];

process.stdin.resume();
process.stdin.setEncoding('utf8');

process.stdin.on('data', function(data) {
  process.stdout.write(
    decrypt(data, key)
  );
});

