#!/usr/bin/env node

require("6to5/register")

var Encryptor = require("./src/Encryptor");
var key       = process.argv.slice(2)[0]

process.stdin.setEncoding('utf8')
process.stdin.resume()

process.stdin.pipe(new Encryptor(key))
             .pipe(process.stdout)
