namespace :JavaScript6 do
  task :clean do
  end

  task :check do
    `which npm`

    unless $?.success?
      raise "Could not locate a suitable JavaScript compiler, please run `brew install node`"
    end
  end

  task :build => :check do
    path = File.dirname(__FILE__)
    `cd #{ path }; npm install --quiet`
  end

end

task :default => 'JavaScript6:build'
