task :default => "Go:build"

namespace :Go do

  task :check do
    `which go`
    raise "Please ensure that you have Go installed" unless $?.success?
  end

  task :clean do
    path = File.dirname(File.expand_path(__FILE__))
    `cd #{path}; rm -f encrypt decrypt`
  end

  task :build do
    path = File.dirname(File.expand_path(__FILE__))
    `export GOPATH=#{path}; cd #{path}; go build -o ./encrypt ./src/encrypt.go`
    `export GOPATH=#{path}; cd #{path}; go build -o ./decrypt ./src/decrypt.go`
  end
end
