namespace :D do
  def run_command(command)
    path   = File.dirname(__FILE__)
    output = `cd "#{path}"; #{command}`

    raise "Command failed: '#{command}': #{output}" unless $?.success?
  end

  desc "Check to see if we can build the programs"
  task :check do
    `which dmd`

    unless $?.success?
      raise "Could not locate a suitable D compiler, please run `brew install dmd`"
    end
  end

  task :build => :check do
    run_command(%(dmd -w encrypt.d encrypter.d utility.d key_parsing.d))
    run_command(%(dmd -w decrypt.d decrypter.d utility.d key_parsing.d))
  end

  task :clean do
    run_command(%(rm -f *.o encrypt decrypt))
  end
end

task :default => :build